IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'USERS')
BEGIN
	CREATE TABLE USERS
	(
		ID int IDENTITY(1,1) PRIMARY KEY,
		EMAIL nvarchar(255) UNIQUE NOT NULL,
		USERNAME nvarchar(100) NOT NULL,
		PASSWORD binary(256),
		SALT binary(32),
		VERIFIED bit NOT NULL DEFAULT 0,
		SIGNUPDATE datetime NOT NULL DEFAULT GETDATE()
	);
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'USERTOKENS')
BEGIN
	CREATE TABLE USERTOKENS
	(
		ID int IDENTITY(1,1) PRIMARY KEY,
		USERID_FK int NOT NULL FOREIGN KEY REFERENCES USERS(ID),
		TOKEN uniqueidentifier NOT NULL,
		TOKENTYPE int NOT NULL,
		CREATEDATE datetime NOT NULL DEFAULT GETDATE(),
	);
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CAMPAIGNS')
BEGIN
	CREATE TABLE CAMPAIGNS
	(
		ID int IDENTITY(1,1) PRIMARY KEY,
		USERID_FK int NOT NULL FOREIGN KEY REFERENCES USERS(ID),
		NAME nvarchar(255) NOT NULL,
		CREATEDATE datetime NOT NULL DEFAULT GETDATE(),
	);
END
GO